version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: lts
    main: ./main.go
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    flags:
      - -trimpath

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: lts
    repository:
      owner: benfdking
      name: lts
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/benfdking/lts"
    description: "Convert natural language to shell commands using AI"
    license: "MIT"
    install: |
      bin.install "lts"

release:
  github:
    owner: benfdking
    name: lts
  extra_files:
    - glob: ./install.sh

# Universal installation script
announce:
  skip: false

# Generate install script
blobs:
  - provider: s3
    bucket: "{{ .Env.AWS_BUCKET }}"
    directory: "{{ .ProjectName }}/{{ .Version }}"