# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lts < Formula
  desc "Convert natural language to shell commands using AI"
  homepage "https://github.com/benfdking/lts"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benfdking/lts/releases/download/v0.0.9/lts_Darwin_x86_64.tar.gz"
      sha256 "a6ae9ac2437309fb4d908c5fc111f233da68754d94b043deae4185f4aab95ea4"

      def install
        bin.install "lts" => "lts-bin"
        bin.install "lts-wrapper.sh" => "lts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benfdking/lts/releases/download/v0.0.9/lts_Darwin_arm64.tar.gz"
      sha256 "8b504e1f2840b29700b8f4fcf8ceecaa8157356c086c921d923deedf72ea4ccd"

      def install
        bin.install "lts" => "lts-bin"
        bin.install "lts-wrapper.sh" => "lts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benfdking/lts/releases/download/v0.0.9/lts_Linux_x86_64.tar.gz"
      sha256 "fe81fbc7c3e29d2e02e28d70890d9303422369594df4dcbb302051167f686933"
      def install
        bin.install "lts" => "lts-bin"
        bin.install "lts-wrapper.sh" => "lts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benfdking/lts/releases/download/v0.0.9/lts_Linux_arm64.tar.gz"
      sha256 "3205061146a909cddb310f039a3df136f670cd705ab7a2a811b89fb195f72f37"
      def install
        bin.install "lts" => "lts-bin"
        bin.install "lts-wrapper.sh" => "lts"
      end
    end
  end

  def caveats
    <<~EOS
      LTS has been installed with interactive command execution enabled by default.

      When you run 'lts', it will:
      1. Generate the command using AI
      2. Show you the command
      3. Prompt "Execute? (y/N)" for confirmation
      4. Run the command if you confirm

      For scripting or piping, use the --raw flag:
        lts --raw list all pdf files

      Run 'lts init' to configure your LLM provider.
    EOS
  end
end
