# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lts < Formula
  desc "Convert natural language to shell commands using AI"
  homepage "https://github.com/benfdking/lts"
  version "0.0.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benfdking/lts/releases/download/v0.0.11/lts_Darwin_x86_64.tar.gz"
      sha256 "5a359b2cc516e58334c3ba4e7b74b576335727af37e61cd920e9574d0311da3b"

      def install
        bin.install "lts" => "lts-bin"
        bin.install "lts-wrapper.sh" => "lts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benfdking/lts/releases/download/v0.0.11/lts_Darwin_arm64.tar.gz"
      sha256 "fd93a5f22b60c7ce403b8f6414db92942de0fbe9169cca3c6e0166eb0363ba7f"

      def install
        bin.install "lts" => "lts-bin"
        bin.install "lts-wrapper.sh" => "lts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benfdking/lts/releases/download/v0.0.11/lts_Linux_x86_64.tar.gz"
      sha256 "31754f3dfd2fe827989c7e7498620d08d8ee08c82ed65d44f752663017809531"
      def install
        bin.install "lts" => "lts-bin"
        bin.install "lts-wrapper.sh" => "lts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benfdking/lts/releases/download/v0.0.11/lts_Linux_arm64.tar.gz"
      sha256 "cecc7ce4e7052cdc16b2bfc49fc9844828b8513f64c4a3f5fe6d64ac002fe752"
      def install
        bin.install "lts" => "lts-bin"
        bin.install "lts-wrapper.sh" => "lts"
      end
    end
  end

  def caveats
    <<~EOS
      LTS has been installed with interactive command execution enabled by default.

      When you run 'lts', it will:
      1. Generate the command using AI
      2. Show you the command
      3. Prompt "Execute? (y/N)" for confirmation
      4. Run the command if you confirm

      For scripting or piping, use the --raw flag:
        lts --raw list all pdf files

      Run 'lts init' to configure your LLM provider.
    EOS
  end
end
