# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lts < Formula
  desc "Convert natural language to shell commands using AI"
  homepage "https://github.com/benfdking/lts"
  version "0.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benfdking/lts/releases/download/v0.0.12/lts_Darwin_x86_64.tar.gz"
      sha256 "6aebadf93872776e4a808a3dd4e18d04609a16b1f82cc269ae6855064e2ec4b4"

      def install
        bin.install "lts" => "lts-bin"
        bin.install "lts-wrapper.sh" => "lts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benfdking/lts/releases/download/v0.0.12/lts_Darwin_arm64.tar.gz"
      sha256 "006c2fdb366919d2a12be448a46f8c325abac7cd2a2912e4fb28f2609ef4b148"

      def install
        bin.install "lts" => "lts-bin"
        bin.install "lts-wrapper.sh" => "lts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benfdking/lts/releases/download/v0.0.12/lts_Linux_x86_64.tar.gz"
      sha256 "16e98ace949bff1d3578c0955db0e9204370fa419a2aa98659786975192e9947"
      def install
        bin.install "lts" => "lts-bin"
        bin.install "lts-wrapper.sh" => "lts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benfdking/lts/releases/download/v0.0.12/lts_Linux_arm64.tar.gz"
      sha256 "021c69b9e8c78bb1afe91d0a694060081a1a51505f6be1a7b432ea5a61419be3"
      def install
        bin.install "lts" => "lts-bin"
        bin.install "lts-wrapper.sh" => "lts"
      end
    end
  end

  def caveats
    <<~EOS
      LTS has been installed with interactive command execution enabled by default.

      When you run 'lts', it will:
      1. Generate the command using AI
      2. Show you the command
      3. Prompt "Execute? (y/N)" for confirmation
      4. Run the command if you confirm

      For scripting or piping, use the --raw flag:
        lts --raw list all pdf files

      Run 'lts init' to configure your LLM provider.
    EOS
  end
end
